### ISSUE TITLE
Error has installed workflow in redmine 6.0.3

### ISSUE THREAD

**Issue by knitdv** [anteo/redmine_custom_workflows#355]
When I try to access the settings, I get an error.

``` Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

[Back](javascript:history.back())
```

```redmine-1   | I, [2025-02-04T07:28:13.353578 #1]  INFO -- : [5039ced3-5d89-4cb3-a6f6-f3b5e061c11f] Processing by RolesController#new as HTML
redmine-1   | I, [2025-02-04T07:28:13.358794 #1]  INFO -- : [5039ced3-5d89-4cb3-a6f6-f3b5e061c11f]   Current user: admin (id=1)
redmine-1   | I, [2025-02-04T07:28:13.395444 #1]  INFO -- : [5039ced3-5d89-4cb3-a6f6-f3b5e061c11f]   Rendered layout layouts/admin.html.erb (Duration: 30.0ms | GC: 0.0ms)
redmine-1   | I, [2025-02-04T07:28:13.395819 #1]  INFO -- : [5039ced3-5d89-4cb3-a6f6-f3b5e061c11f] Completed 200 OK in 42ms (Views: 27.8ms | ActiveRecord: 5.3ms (11 queries, 0 
cached) | GC: 0.0ms)
redmine-1   | I, [2025-02-04T07:28:22.805368 #1]  INFO -- : [4ddb552a-a271-4453-afc7-59780495236c] Started GET "/custom_workflows" for 172.20.0.1 at 2025-02-04 07:28:22 +0000
redmine-1   | I, [2025-02-04T07:28:22.806066 #1]  INFO -- : [4ddb552a-a271-4453-afc7-59780495236c] Processing by CustomWorkflowsController#index as HTML
redmine-1   | I, [2025-02-04T07:28:22.810783 #1]  INFO -- : [4ddb552a-a271-4453-afc7-59780495236c]   Current user: admin (id=1)
postgres-1  | 2025-02-04 07:28:22.811 UTC [37] ERROR:  relation "custom_workflows" does not exist at character 523
postgres-1  | 2025-02-04 07:28:22.811 UTC [37] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),
postgres-1  |          pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,
postgres-1  |          c.collname, col_description(a.attrelid, a.attnum) AS comment,
postgres-1  |          attidentity AS identity,
postgres-1  |          attgenerated as attgenerated
postgres-1  |     FROM pg_attribute a
postgres-1  |     LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
postgres-1  |     LEFT JOIN pg_type t ON a.atttypid = t.oid
postgres-1  |     LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
postgres-1  |    WHERE a.attrelid = '"custom_workflows"'::regclass
postgres-1  |      AND a.attnum > 0 AND NOT a.attisdropped
postgres-1  |    ORDER BY a.attnum
postgres-1  | 
redmine-1   | I, [2025-02-04T07:28:22.812578 #1]  INFO -- : [4ddb552a-a271-4453-afc7-59780495236c] Completed 500 Internal Server Error in 6ms (ActiveRecord: 2.1ms (3 queries, 0
 cached) | GC: 0.0ms)
redmine-1   | F, [2025-02-04T07:28:22.812923 #1] FATAL -- : [4ddb552a-a271-4453-afc7-59780495236c]
redmine-1   | [4ddb552a-a271-4453-afc7-59780495236c] ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "custom_workflows" does not exist
redmine-1   | LINE 10:  WHERE a.attrelid = '"custom_workflows"'::regclass
redmine-1   |                              ^
redmine-1   | ):
redmine-1   | [4ddb552a-a271-4453-afc7-59780495236c]
redmine-1   | Causes:
redmine-1   | [4ddb552a-a271-4453-afc7-59780495236c] PG::UndefinedTable (ERROR:  relation "custom_workflows" does not exist
redmine-1   | LINE 10:  WHERE a.attrelid = '"custom_workflows"'::regclass
redmine-1   |                              ^
redmine-1   | )
redmine-1   | [4ddb552a-a271-4453-afc7-59780495236c]
```

Redmine run in docker.

docker-compose.yml
```
version: '3.1'

services:

  postgres:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redmine
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata

  redmine:
    image: redmine:6.0
    restart: always
    ports:
      - 80:3000
    environment:
      REDMINE_DB_POSTGRES: postgres
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine
      REDMINE_SECRET_KEY_BASE: SecretKey2025
    depends_on:
      - postgres
    volumes:
       - ./redmine_data/redmine-plugins:/usr/src/redmine/plugins
       - ./redmine_data/redmine-themes:/usr/src/redmine/public/themes
       - ./redmine_data/redmine-data:/usr/src/redmine/files
      
  ```
